title: Krutartha Nagesh
logo: /assets/img/potrait.jpg
description: Computer scientist, engineer, guitar player
show_downloads: true
location: Syracuse, NY
google_analytics:
theme: jekyll-theme-minimal
